[input]
sensitivity = 0.5
pause_threshold = 0.8
energy_threshold = 300
dynamic_energy_threshold = true
dynamic_energy_adjustment_damping = 0.15
keywords = ["jarvis"]
lang = "de-DE"
play_bling_before_listen = false

[output]
samplerate = 44100
channels = 2
