established = false

system_name = "JARVIS"

default_user = ""

[local_storage]
home_location = ""
actual_location = ""

[keys]
messenger = ""

[services]

[services.activation]
messenger = true
ai = false

[services.philips-hue]
Bridge-IP = ""

[services.philips-tv]
user = ""
pass = ""
host = ""

[audio]

[audio.input]
device_index = -1
sensitivity = 0.5
pause_threshold = 0.8
energy_threshold = 300
dynamic_energy_threshold = true
dynamic_energy_adjustment_damping = 0.15
keywords = ["jarvis"]
lang = "de-DE"
play_bling_before_listen = false

[audio.output]
samplerate = 44100
channels = 2
voice = "male"

[api]
open_weather_map = "bd4d17c6eedcff6efc70b9cefda99082"
porcupine = ""

[change_output]
timer = "timer"